language: php

php:
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'

before_install:
    - composer install --dev
    #- composer update --no-dev

script:
    - vendor/bin/phpunit
    #- phpunit
